study:
  countries:
    - UK
    - BE
    - NL
  age_groups:
    - "0-9"
    - "10-19"
    - "20-29"
    - "30-39"
    - "40-49"
    - "50-59"
    - "60-69"
    - "70+"
  infectivity:
    - 0.54     # 0-9
    - 0.55     # 10-19
    - 0.59     # 20-29
    - 0.70     # 30-39
    - 0.76     # 40-49
    - 0.90     # 50-59
    - 0.99     # 60-69
    - 0.99     # 70+
  n_sample: 30
  m_effect: 0.15 #0.15
  boot: TRUE # Whether to perform bootstrapping to estimate contact matrices

data_paths:
  incidence: "data_raw/incidence/"
  contacts: "data_raw/contacts/"
  measures: "data_raw/measures/"
  rt: "data_raw/rt/"

results_path: "results/"
data_processed: "data_processed/"
