# script to obtain social contact matrices for BE, UK and NL during the COVID-19 pandemic

run_cm = function(participants, contacts, n_sample, aux_country,age_numeric) {
  # Generates a sample of social contact matrices with the socialmixr package
  
  # INPUT: participant and contacts dataframe with the same structure as in socialmixr and the number of desired samples
  # OUTPUT: contact matrix generated by socialmixr for each setting
  
  
  # progress bar
  pb <- txtProgressBar(min = 0, max = n_sample, style = 3)  # style=3 gives a nice bar
  
  # Create a survey object
  survey_=survey(participants=participants,
                 contacts=contacts)
  res=list()
  aux_home=list()
  aux_school=list()
  aux_work=list()
  aux_transport=list()
  aux_leisure=list()
  aux_other=list()
  
  cm_home=list()
  cm_school=list()
  cm_work=list()
  cm_transport=list()
  cm_leisure=list()
  cm_other=list()
  cm_total=list()
  
  dem=list()
  part=list()
  
  # boostrap?
  boot=FALSE
  
  for (i in 1:n_sample) {
    # home
    set.seed(i)
    aux_home[[i]]=socialmixr::contact_matrix(survey_,
                                             countries = aux_country,
                                             return.demography = TRUE,
                                             age.limits = age_numeric,
                                             estimated.participant.age = "sample",
                                             estimated.contact.age = "sample",
                                             missing.contact.age = "remove",
                                             missing.participant.age = "remove",
                                             weigh.age=TRUE, 
                                             weigh.dayofweek=TRUE,
                                             weight.threshold = 3,
                                             sample.participants = boot,
                                             filter = list(cnt_home = 1))
    
    
    
    cm_home[[i]] = aux_home[[i]]$matrix
    
    # school
    set.seed(i)
    aux_school[[i]]=socialmixr::contact_matrix(survey_,
                                               countries = aux_country,
                                               return.demography = TRUE,
                                               age.limits = age_numeric,
                                               estimated.participant.age = "sample",
                                               estimated.contact.age = "sample",
                                               missing.contact.age = "remove",
                                               missing.participant.age = "remove",
                                               weigh.age=TRUE, 
                                               weigh.dayofweek=TRUE,
                                               weight.threshold = 3,
                                               sample.participants = boot,
                                               filter = list(cnt_school = 1))
    
    
    
    cm_school[[i]] = aux_school[[i]]$matrix
    
    
    # work
    set.seed(i)
    aux_work[[i]]=socialmixr::contact_matrix(survey_,
                                             countries = aux_country,
                                             return.demography = TRUE,
                                             age.limits = age_numeric,
                                             estimated.participant.age = "sample",
                                             estimated.contact.age = "sample",
                                             missing.contact.age = "remove",
                                             missing.participant.age = "remove",
                                             weigh.age=TRUE, 
                                             weigh.dayofweek=TRUE,
                                             weight.threshold = 3,
                                             sample.participants = boot,
                                             filter = list(cnt_work = 1))
    
    
    
    cm_work[[i]] = aux_work[[i]]$matrix
    
    
    # transport
    set.seed(i)
    aux_transport[[i]]=socialmixr::contact_matrix(survey_,
                                                  countries = aux_country,
                                                  return.demography = TRUE,
                                                  age.limits = age_numeric,
                                                  estimated.participant.age = "sample",
                                                  estimated.contact.age = "sample",
                                                  missing.contact.age = "remove",
                                                  missing.participant.age = "remove",
                                                  weigh.age=TRUE, 
                                                  weigh.dayofweek=TRUE,
                                                  weight.threshold = 3,
                                                  sample.participants = boot,
                                                  filter = list(cnt_transport= 1))
    
    
    
    cm_transport[[i]] = aux_transport[[i]]$matrix
    
    # leisure
    set.seed(i)
    aux_leisure[[i]]=socialmixr::contact_matrix(survey_,
                                                countries = aux_country,
                                                return.demography = TRUE,
                                                age.limits = age_numeric,
                                                estimated.participant.age = "sample",
                                                estimated.contact.age = "sample",
                                                missing.contact.age = "remove",
                                                missing.participant.age = "remove",
                                                weigh.age=TRUE, 
                                                weigh.dayofweek=TRUE,
                                                weight.threshold = 3,
                                                sample.participants = boot,
                                                filter = list(cnt_leisure= 1))
    
    
    
    cm_leisure[[i]] = aux_leisure[[i]]$matrix
    
    # otherplace
    set.seed(i)
    aux_other[[i]]=socialmixr::contact_matrix(survey_,
                                              countries = aux_country,
                                              return.demography = TRUE,
                                              age.limits = age_numeric,
                                              estimated.participant.age = "sample",
                                              estimated.contact.age = "sample",
                                              missing.contact.age = "remove",
                                              missing.participant.age = "remove",
                                              weigh.age=TRUE, 
                                              weigh.dayofweek=TRUE,
                                              weight.threshold = 3,
                                              sample.participants = boot,
                                              filter = list(cnt_otherplace= 1))
    
    
    
    cm_other[[i]] = aux_other[[i]]$matrix
    
    # total
    cm_total[[i]] = aux_home[[i]]$matrix+aux_other[[i]]$matrix+aux_school[[i]]$matrix+aux_work[[i]]$matrix+aux_transport[[i]]$matrix+aux_leisure[[i]]$matrix
    
    
    # extract the participants and demography (same across settings)
    part[[i]]= aux_home[[i]]$participants
    dem[[i]]=aux_home[[i]]$demography
    
    #progress bar
    setTxtProgressBar(pb, i)
    
  }
  
  # compute the mean matrix and standard deviation matrix for each setting
  
  # home
  cm_mean_home=Reduce("+",cm_home)/length(cm_home)
  cm_sd_home=sqrt(Reduce("+",lapply(cm_home, function(x) (x - cm_mean_home)^2))/length(cm_home))
  
  # school
  cm_mean_school=Reduce("+",cm_school)/length(cm_school)
  cm_sd_school=sqrt(Reduce("+",lapply(cm_school, function(x) (x - cm_mean_school)^2))/length(cm_school))
  
  # work
  cm_mean_work=Reduce("+",cm_work)/length(cm_work)
  cm_sd_work=sqrt(Reduce("+",lapply(cm_work, function(x) (x - cm_mean_work)^2))/length(cm_work))
  
  # transport
  cm_mean_transport=Reduce("+",cm_transport)/length(cm_transport)
  cm_sd_transport=sqrt(Reduce("+",lapply(cm_transport, function(x) (x - cm_mean_transport)^2))/length(cm_transport))
  
  # leisure
  cm_mean_leisure=Reduce("+",cm_leisure)/length(cm_leisure)
  cm_sd_leisure=sqrt(Reduce("+",lapply(cm_leisure, function(x) (x - cm_mean_leisure)^2))/length(cm_leisure))
  
  # other
  cm_mean_other=Reduce("+",cm_other)/length(cm_other)
  cm_sd_other=sqrt(Reduce("+",lapply(cm_other, function(x) (x - cm_mean_other)^2))/length(cm_other))
  
  # total
  cm_mean_total=Reduce("+",cm_total)/length(cm_total)
  cm_sd_total=sqrt(Reduce("+",lapply(cm_total, function(x) (x - cm_mean_total)^2))/length(cm_total))
  
  res$matrix_sample_home = cm_home
  res$matrix_mean_home = cm_mean_home
  res$matrix_sd_home = cm_sd_home
  
  
  res$matrix_sample_school = cm_school
  res$matrix_mean_school = cm_mean_school
  res$matrix_sd_school = cm_sd_school
  
  res$matrix_sample_work = cm_work
  res$matrix_mean_work = cm_mean_work
  res$matrix_sd_work = cm_sd_work
  
  res$matrix_sample_transport = cm_transport
  res$matrix_mean_transport = cm_mean_transport
  res$matrix_sd_transport = cm_sd_transport
  
  res$matrix_sample_leisure = cm_leisure
  res$matrix_mean_leisure = cm_mean_leisure
  res$matrix_sd_leisure = cm_sd_leisure
  
  res$matrix_sample_other = cm_other
  res$matrix_mean_other = cm_mean_other
  res$matrix_sd_other = cm_sd_other
  
  res$matrix_sample_total = cm_total
  res$matrix_mean_total = cm_mean_total
  res$matrix_sd_total = cm_sd_total
  
  res$participants = part
  res$demography = dem
  
  close(pb)
  return(res)
}



build_contact_matrices=function(country,raw_data,n_sample,age_groups){
  
  age_numeric <- as.numeric(sub("[-+].*", "", age_groups))
  
  if(country=="UK"){
    aux_country="United Kingdom"
  } else if(country=="BE"){
    aux_country="Belgium"
  } else if(country=="NL"){
    aux_country="Netherlands"
  }
  
  participants = raw_data$participants
  contacts = raw_data$contacts
  
  CM = participants %>%
        split(.$period) %>%
        map(~run_cm(.x,contacts, n_sample,aux_country,age_numeric))
  
  return(CM)
}