# script to obtain social contact matrices for BE, UK and NL during the COVID-19 pandemic

run_cm = function(participants, contacts, n_sample, aux_country,age_numeric, boot) {
  # Generates a sample of social contact matrices with the socialmixr package
  
  # INPUT: participant and contacts dataframe with the same structure as in socialmixr and the number of desired samples
  # OUTPUT: contact matrix generated by socialmixr for each setting
  
  
  # progress bar
  pb <- txtProgressBar(min = 0, max = n_sample, style = 3)  # style=3 gives a nice bar
  
  # Create a survey object
  survey_=survey(participants=participants,
                 contacts=contacts)
  res=list()
  aux_home=list()
  aux_school=list()
  aux_work=list()
  aux_transport=list()
  aux_leisure=list()
  aux_other=list()
  
  cm_home=list()
  cm_school=list()
  cm_work=list()
  cm_transport=list()
  cm_leisure=list()
  cm_other=list()
  cm_total=list()
  
  dem=list()
  part=list()

  
  for (i in 1:n_sample) {
    # home
    set.seed(i)
    aux_home[[i]]=socialmixr::contact_matrix(survey_,
                                             countries = aux_country,
                                             return_demography = TRUE,
                                             age_limits = age_numeric,
                                             estimated_participant_age = "sample",
                                             estimated_contact_age = "sample",
                                             missing_contact_age = "remove",
                                             missing_participant_age = "remove",
                                             weigh_age=TRUE, 
                                             weigh_dayofweek=TRUE,
                                             sample_participants = boot,
                                             filter = list(cnt_home = 1))
    
    
    
    cm_home[[i]] = aux_home[[i]]$matrix
    
    # school
    set.seed(i)
    aux_school[[i]]=socialmixr::contact_matrix(survey_,
                                               countries = aux_country,
                                               return_demography = TRUE,
                                               age_limits = age_numeric,
                                               estimated_participant_age = "sample",
                                               estimated_contact_age = "sample",
                                               missing_contact_age = "remove",
                                               missing_participant_age = "remove",
                                               weigh_age=TRUE, 
                                               weigh_dayofweek=TRUE,
                                               sample_participants = boot,
                                               filter = list(cnt_school = 1))
    
    
    
    cm_school[[i]] = aux_school[[i]]$matrix
    
    
    # work
    set.seed(i)
    aux_work[[i]]=socialmixr::contact_matrix(survey_,
                                             countries = aux_country,
                                             return_demography = TRUE,
                                             age_limits = age_numeric,
                                             estimated_participant_age = "sample",
                                             estimated_contact_age = "sample",
                                             missing_contact_age = "remove",
                                             missing_participant_age = "remove",
                                             weigh_age=TRUE, 
                                             weigh_dayofweek=TRUE,
                                             sample_participants = boot,
                                             filter = list(cnt_work = 1))
    
    
    
    cm_work[[i]] = aux_work[[i]]$matrix
    
    
    # transport
    set.seed(i)
    aux_transport[[i]]=socialmixr::contact_matrix(survey_,
                                                  countries = aux_country,
                                                  return_demography = TRUE,
                                                  age_limits = age_numeric,
                                                  estimated_participant_age = "sample",
                                                  estimated_contact_age = "sample",
                                                  missing_contact_age = "remove",
                                                  missing_participant_age = "remove",
                                                  weigh_age=TRUE, 
                                                  weigh_dayofweek=TRUE,
                                                  sample_participants = boot,
                                                  filter = list(cnt_transport= 1))
    
    
    
    cm_transport[[i]] = aux_transport[[i]]$matrix
    
    # leisure
    set.seed(i)
    aux_leisure[[i]]=socialmixr::contact_matrix(survey_,
                                                countries = aux_country,
                                                return_demography = TRUE,
                                                age_limits = age_numeric,
                                                estimated_participant_age = "sample",
                                                estimated_contact_age = "sample",
                                                missing_contact_age = "remove",
                                                missing_participant_age = "remove",
                                                weigh_age=TRUE, 
                                                weigh_dayofweek=TRUE,
                                                sample_participants = boot,
                                                filter = list(cnt_leisure= 1))
    
    
    
    cm_leisure[[i]] = aux_leisure[[i]]$matrix
    
    # otherplace
    set.seed(i)
    aux_other[[i]]=socialmixr::contact_matrix(survey_,
                                              countries = aux_country,
                                              return_demography = TRUE,
                                              age_limits = age_numeric,
                                              estimated_participant_age = "sample",
                                              estimated_contact_age = "sample",
                                              missing_contact_age = "remove",
                                              missing_participant_age = "remove",
                                              weigh_age=TRUE, 
                                              weigh_dayofweek=TRUE,
                                              sample_participants = boot,
                                              filter = list(cnt_otherplace= 1))
    
    
    
    cm_other[[i]] = aux_other[[i]]$matrix
    
    # total
    cm_total[[i]] = aux_home[[i]]$matrix+aux_other[[i]]$matrix+aux_school[[i]]$matrix+aux_work[[i]]$matrix+aux_transport[[i]]$matrix+aux_leisure[[i]]$matrix
    
    
    # extract the participants and demography (same across settings)
    part[[i]]= aux_home[[i]]$participants
    dem[[i]]=aux_home[[i]]$demography
    
    #progress bar
    setTxtProgressBar(pb, i)
    
  }
  
  res$matrix_sample_home = cm_home
  res$matrix_sample_school = cm_school
  res$matrix_sample_work = cm_work
  res$matrix_sample_transport = cm_transport
  res$matrix_sample_leisure = cm_leisure
  res$matrix_sample_other = cm_other
  res$matrix_sample_total = cm_total
  
  res$participants = part
  res$demography = dem
  
  close(pb)
  return(res)
}



build_contact_matrices=function(country,raw_data,n_sample,age_groups, boot){
  
  age_numeric <- as.numeric(sub("[-+].*", "", age_groups)) # extract the lower bound of the age groups and convert to numeric
  
  if(country=="UK"){
    aux_country="United Kingdom"
  } else if(country=="BE"){
    aux_country="Belgium"
  } else if(country=="NL"){
    aux_country="Netherlands"
  }
  
  participants = raw_data$participants
  contacts = raw_data$contacts
  
  CM = participants %>%
        split(.$period) %>%
        map(~run_cm(.x,contacts, n_sample,aux_country,age_numeric,boot=boot))
  
  return(CM)
}